---
name: "Does The Dog Die"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net9.0"
overview: "Display content warnings from DoesTheDogDie.com"
description: >
  Integrates with DoesTheDogDie.com to display content warnings
  and trigger information for movies and TV shows in Jellyfin.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.DoesTheDogDie.dll"
changelog: >
  changelog
