---
name: "Does The Dog Die"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "0.1.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Display content warnings from DoesTheDogDie.com"
description: >
  Integrates with DoesTheDogDie.com to display content warnings
  and trigger information for movies and TV shows in Jellyfin.
  Fetches triggers (animal death, violence, jump scares, etc.)
  and adds them as metadata tags to movies and TV shows.
category: "General"
owner: "theflanman"
artifacts:
- "Jellyfin.Plugin.DoesTheDogDie.dll"
changelog: |
  - Initial release with DoesTheDogDie.com integration
  - Hierarchical trigger filtering (categories and topics)
  - Content warning tags (CW:) and safe tags (Safe:)
  - Background service for automatic lookups
  - Scheduled task for periodic refresh
  - External ID and URL providers
